In [45]:
from trout.intra.year import Year
from trout.intra.night import Night

import numpy as np

In [30]:
a = Year(2009)

In [35]:
# choose a night a random
import random
night = random.choice(a.nights)

In [36]:
night

August 10, 2009

In [ ]:
# We are going to use this night from now on

In [37]:
# Note that this is a Night instance not a date instance,
# althought you could do things like get date instance from 
# the night

print(type(night))
print(night.night_date)

<class 'trout.intra.night.Night'>
2009-08-10


In [ ]:
# There are quite a few details of the data processing that we
# see for this night

In [38]:
# 1. Alignment statitstics for the images

In [39]:
b.alignment_stats

Image_Name  Rotation  Translation_X  Translation_Y  Scale
0    m23_7.0-001.fit -0.030451         72.410        128.194  0.881
1    m23_7.0-002.fit -0.030580         72.666        128.031  0.881
2    m23_7.0-003.fit -0.030695         73.133        127.758  0.881
3    m23_7.0-004.fit -0.030496         73.601        126.621  0.881
4    m23_7.0-005.fit -0.030827         74.324        126.376  0.881
..               ...       ...            ...            ...    ...
195  m23_7.0-196.fit -0.031610          9.366        131.911  0.881
196  m23_7.0-197.fit -0.031566          9.350        131.709  0.880
197  m23_7.0-198.fit -0.031431         10.051        130.546  0.881
198  m23_7.0-199.fit -0.031491         10.586        130.127  0.880
199  m23_7.0-200.fit -0.031216         11.075        128.755  0.881

[200 rows x 5 columns]

In [40]:
# If we want access to aligned combined images data
# we can do that too

In [41]:
# We choose a alignmened combined image at random
ac = random.choice(night.aligned_combined)

In [48]:
# Let's peek at the center of the data, and find it's 
# min, max, median, mean, std, etc.
print(ac.data[400:600, 400:600])
print(np.mean(ac.data))
print(np.median(ac.data))
print(np.std(ac.data))

[[6432 6427 6576 ... 6503 6382 6281]
 [6464 6406 6522 ... 6533 6420 6358]
 [6592 6669 6595 ... 6496 6444 6342]
 ...
 [6503 6449 6451 ... 6518 6253 6307]
 [6484 6455 6475 ... 6441 6321 6410]
 [6475 6411 6483 ... 6370 6489 6404]]
5080.748371124268
6371.0
3512.796781072879


In [50]:
# Lets take a look at logfile combined file
# We'll choose the 5th file this time.
lg = night.logfile_combined[4]
print(lg)

Night: August 10, 2009. 08-10-09_m23_3.5-005.txt


In [51]:
lg.data

X       Y   XFWHM   YFWHM  Avg FWHM  Sky ADU  Star ADU 3  \
Star_no                                                                  
1        746.16  459.05  3.8121  3.0637    3.4379  2724.93  7303334.30   
2        546.99  493.73  3.1074  2.6875    2.8975  2733.84  3471995.89   
3        462.55  522.91  3.1032  3.1563    3.1298  2727.25  3412909.78   
4        230.27  347.33  2.7976  3.0444    2.9210  2692.79  2967035.70   
5        112.02  420.06  3.0828  3.7387    3.4108  2688.47  2556973.23   
...         ...     ...     ...     ...       ...      ...         ...   
2506     360.44  979.31  0.0000  0.0000    0.0000   679.50   -19705.64   
2507     515.38  980.95  0.0000  0.0000    0.0000     0.00        0.00   
2508      39.31  732.44  0.0000  0.0000    0.0000     0.00        0.00   
2509     700.89  175.12  9.2459  3.8025    6.5242  2692.23    63504.98   
2510     542.98  642.03  4.1857  5.1589    4.6723  2711.71     2074.57   

         Star ADU 4  Star ADU 5  
Star_no                          
1        8298143.75  8894152.09  
2        3739520.58  3876673.07  
3        3669723.33  3768651.25  
4        3178861.97  3269177.70  
5        2798528.17  2873811.29  
...             ...         ...  
2506      -33295.73   -55039.89  
2507           0.00        0.00  
2508           0.00        0.00  
2509      118276.22   232188.05  
2510        2372.99     2400.96  

[2510 rows x 9 columns]

In [58]:
# Let's get all FWHM for the stars and find average for the night
fwhm_x = {star: [] for star in range(1, 2511)} # Make empty containers
fwhm_y = {star: [] for star in range(1, 2511)} 
for file in night.logfile_combined:
    data = file.data
    for star_no in range(1, 2510): 
        xfwhm = data.loc[star_no, "XFWHM"]
        yfwhm = data.loc[star_no, "XFWHM"]
        if xfwhm > 0:
            fwhm_x[star_no].append(xfwhm)
        if yfwhm > 0:
            fwhm_y[star_no].append(yfwhm)

In [59]:
fwhm_x_avg = {star : np.median(fwhm_x[star]) for star in fwhm_x}
fwhm_y_avg = {star : np.median(fwhm_y[star]) for star in fwhm_y}

/opt/tljh/user/lib/python3.9/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/opt/tljh/user/lib/python3.9/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


In [61]:
# We could then compare these FWHM to another night, or another year

In [62]:
# For eclipsing binary stars, you might want to look at the flux logs 
# combined. You can do that too from here

In [69]:
# 16 is an EB
s16 = night.get_star_fluxlog_for_radius(star_no=16, radius=4)

In [70]:
s16.data

ADU       X       Y     Norm             Datetime
0   1652405.43  700.77  685.85  1.02185  2009-08-11T04:47:52
1   1651197.39  700.77  685.85  1.02924  2009-08-11T04:50:43
2   1660950.12  700.73  685.83  0.99608  2009-08-11T04:53:33
3   1653714.40  700.74  685.86  0.97124  2009-08-11T04:56:25
4   1647014.53  700.76  685.86  1.00609  2009-08-11T04:59:16
5   1650294.17  700.76  685.87  0.96368  2009-08-11T05:02:07
6   1654612.62  700.74  685.88  0.96002  2009-08-11T05:04:58
7   1648516.32  700.74  685.85  0.96399  2009-08-11T05:07:49
8   1651784.49  700.75  685.86  0.97068  2009-08-11T05:10:40
9   1656042.14  700.73  685.86  0.98780  2009-08-11T05:13:31
10  1644939.31  700.73  685.86  0.98003  2009-08-11T05:16:22
11  1643373.49  700.74  685.87  0.98100  2009-08-11T05:19:13
12  1643822.28  700.72  685.88  0.97759  2009-08-11T05:22:04
13  1642944.31  700.71  685.86  0.99602  2009-08-11T05:24:55
14  1639058.91  700.71  685.88  1.00416  2009-08-11T05:27:46
15  1632415.78  700.72  685.87  1.00754  2009-08-11T05:30:37
16  1613922.98  700.71  685.87  1.01251  2009-08-11T05:33:28
17  1624876.47  700.70  685.86  1.04266  2009-08-11T05:36:19
18  1615950.70  700.70  685.88  1.05277  2009-08-11T05:39:10
19  1598366.42  700.73  685.88  1.06661  2009-08-11T05:42:00
20  1611210.03  700.75  685.91  1.09994  2009-08-11T05:44:54

In [71]:
# You also have access to the color normalized file data from the night

In [74]:
cn = night.get_color_normalized(radius=5)

In [77]:
# Here's the sky background data for the night
# This has a lot of columns (use only what you need)
night.sky_bg

Date  Image_number  First_img  Last_img  Moon_Phase  \
0   2009-08-11T04:47:52            33         33        53     0.67704   
1   2009-08-11T04:50:43            34         33        53     0.67711   
2   2009-08-11T04:53:33            35         33        53     0.67718   
3   2009-08-11T04:56:25            36         33        53     0.67725   
4   2009-08-11T04:59:16            37         33        53     0.67731   
5   2009-08-11T05:02:07            38         33        53     0.67738   
6   2009-08-11T05:04:58            39         33        53     0.67745   
7   2009-08-11T05:07:49            40         33        53     0.67751   
8   2009-08-11T05:10:40            41         33        53     0.67758   
9   2009-08-11T05:13:31            42         33        53     0.67765   
10  2009-08-11T05:16:22            43         33        53     0.67771   
11  2009-08-11T05:19:13            44         33        53     0.67778   
12  2009-08-11T05:22:04            45         33        53     0.67785   
13  2009-08-11T05:24:55            46         33        53     0.67792   
14  2009-08-11T05:27:46            47         33        53     0.67798   
15  2009-08-11T05:30:37            48         33        53     0.67805   
16  2009-08-11T05:33:28            49         33        53     0.67812   
17  2009-08-11T05:36:19            50         33        53     0.67818   
18  2009-08-11T05:39:10            51         33        53     0.67825   
19  2009-08-11T05:42:00            52         33        53     0.67832   
20  2009-08-11T05:44:54            53         33        53     0.67839   

   Moon_Phase_Name  Normalized_cluster_angle  Cluster_Angle_Round  \
0   Waning_Gibbous                        21                   22   
1   Waning_Gibbous                        21                   21   
2   Waning_Gibbous                        21                   21   
3   Waning_Gibbous                        21                   21   
4   Waning_Gibbous                        21                   21   
5   Waning_Gibbous                        21                   20   
6   Waning_Gibbous                        21                   20   
7   Waning_Gibbous                        21                   20   
8   Waning_Gibbous                        21                   19   
9   Waning_Gibbous                        21                   19   
10  Waning_Gibbous                        21                   19   
11  Waning_Gibbous                        21                   18   
12  Waning_Gibbous                        21                   18   
13  Waning_Gibbous                        21                   18   
14  Waning_Gibbous                        21                   17   
15  Waning_Gibbous                        21                   17   
16  Waning_Gibbous                        21                   17   
17  Waning_Gibbous                        21                   16   
18  Waning_Gibbous                        21                   16   
19  Waning_Gibbous                        21                   16   
20  Waning_Gibbous                        21                   15   

    Cluster_Angle  Cluster_Angle_Uncertainty  ...     15_6     15_7     15_8  \
0            21.6                        0.8  ...  3411.14  3380.57  3372.19   
1            21.4                        0.8  ...  3115.13  3267.63  3278.96   
2            21.1                        0.8  ...  2448.81  2509.91  2540.64   
3            20.8                        0.9  ...  2426.45  2396.10  2397.11   
4            20.5                        0.9  ...  2876.46  2867.64  2866.48   
5            20.2                        0.9  ...  2417.01  2408.66  2412.81   
6            19.9                        0.9  ...  2487.69  2465.03  2460.34   
7            19.6                        0.9  ...  2522.05  2498.65  2504.95   
8            19.3                        0.9  ...  2574.98  2546.06  2547.17   
9            19.0                        0.9  ...  2886.21  2855.47  28